### ISSUE TITLE
Filenames with square brackets fail to restore

### ISSUE THREAD

**Issue by tomfitzhenry** [directededge/redsnapper#3]
redsnapper version: commit 7a785e24052556c829cc67305baa4b5fb1762a4a
tarsnap version: 1.0.39

## Steps to reproduce

    $ mkdir example
    $ echo foo > example/foo\[bar\]baz
    $ ls example/
    foo[bar]baz
    $ tarsnap -c -f example example/
    $ tarsnap -t -f example
    example/
    example/foo[bar]baz
    $ redsnapper example

## Expected
`example/foo[bar]baz` to be extracted.

## Actual
`example/foo[bar]baz` is not extracted, and instead an error message is printed:

    tarsnap: example/foo[bar]baz: Not found in archive
    tarsnap: Error exit delayed from previous errors.`

**Comment by scotchi** [comment]
Hmm, as far as I can tell this is a tarsnap bug, but I found a workaround.

**Comment by scotchi** [comment]
I filed an issue with Tarsnap.  I'll wait to see what Colin comes back with.

https://github.com/Tarsnap/tarsnap/issues/329
